name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置镜像标签
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: 登录到私人 Docker Registry
        run: docker login http://82.180.162.50:5000 -u zpw -p zpw123

      - name: 构建 Docker 镜像
        run: docker build . -f Dockerfile -t <PRIVATE_REGISTRY_IP>/timeline:${{ env.IMAGE_TAG }}

      - name: 推送 Docker 镜像到私人 Registry
        run: docker push <PRIVATE_REGISTRY_IP>/timeline:${{ env.IMAGE_TAG }}

      - name: 部署到服务器
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: <SERVER_IP>
          username: <SERVER_USERNAME>
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull <PRIVATE_REGISTRY_IP>/timeline:${{ env.IMAGE_TAG }}
            docker stop timeline || true
            docker rm timeline || true
            docker run -d --name timeline -p 8800:80 <PRIVATE_REGISTRY_IP>/timeline:${{ env.IMAGE_TAG }}
